site_name: MkDocs test
docs_dir: Document

# theme
theme:
  name: material
  language: ja
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # - plantuml_markdown:
  #     server: http://www.plantuml.com/plantuml
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  search:
    lang: 'ja'